version: "3.9"

services:
  shelby:
    container_name: shelby
    image: dunamiscapital/shelby:sandbox
    ports:
      - "15000:8000"
    env_file:
      - config/.env.development
    volumes:
      - ./logs/shelby:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
